main: me.hgg.main.hgg

version: 0.1

name: Hide and Go Gortume

author: ZeGeorge & C0nsole & TyZoid

description: Hide and Go Gortume is a minigame plugin in which one random person is gortume, and they must proceed to kill everyone else in the game, in less then a configurable time.


commands:
    haggadmin:
        description: Admin Command for HAGG
    hagg:
        description: Tp to lobby
    